
service: hospital-staff-management

plugins:
    - serverless-offline
#    - serverless-plugin-optimize

provider:
    name: aws
    runtime: nodejs18.x
    region: eu-central-1
    timeout: 5
    iamRoleStatements:
        - Effect: 'Allow'
          Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
          Resource: 'arn:aws:logs:*:*:*'
    environment:
        ENVIRONMENT: ${env:ENVIRONMENT}
        POSTGRES_HOST: ${env:POSTGRES_HOST}
        POSTGRES_PORT: ${env:POSTGRES_PORT}
        POSTGRES_USER: ${env:POSTGRES_PORT}
        POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
        POSTGRES_NAME: ${env:POSTGRES_NAME}
        COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
        COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
        COGNITO_CLIENT_SECRET: ${env:COGNITO_CLIENT_SECRET}

functions:
    restApi:
        handler: dist/lambda.handler
        events:
            - http:
                method: any
                path: /{proxy+}
            - http:
                method: any
                path: /
