
service: hospital-staff-management

plugins:
    - serverless-offline
    - serverless-plugin-optimize

provider:
    name: aws
    runtime: nodejs18.x
    region: us-east-1
    environment:
        DATABASE_URL: ${env:DATABASE_URL}
        ENVIRONMENT: ${env:ENVIRONMENT}
        POSTGRES_HOST: ${env:POSTGRES_HOST}
        POSTGRES_PORT: ${env:POSTGRES_PORT}
        POSTGRES_USER: ${env:POSTGRES_PORT}
        POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
        POSTGRES_NAME: ${env:POSTGRES_NAME}
        AWS_REGION: ${env:POSTGRES_NAME}

functions:
    main:
        handler: dist/lambda.handler
        events:
            - http:
                method: any
                path: /{proxy+}
            - http:
                method: any
                path: /
