name: Deploy to AWS ECS

on:
    push:
        branches:
            - lab4

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Log in to Amazon ECR
              run: |
                  aws ecr get-login-password --region eu-central-1 | \
                    docker login --username AWS --password-stdin 117984642414.dkr.ecr.eu-central-1.amazonaws.com

            - name: Build Docker image
              run: |
                  docker build -t hospital-staff-api:latest .

            - name: Tag Docker image
              run: |
                  docker tag hospital-staff-api:latest 117984642414.dkr.ecr.eu-central-1.amazonaws.com/hospital-staff-api:latest

            - name: Push Docker image to ECR
              run: |
                  docker push 117984642414.dkr.ecr.eu-central-1.amazonaws.com/hospital-staff-api:latest

            - name: Update ECS Service
              run: |
                  aws ecs update-service \
                    --cluster hospital-staff-cluster \
                    --service hospital-staff-service \
                    --force-new-deployment
